### PR TITLE
WINDUP-2855 Moved to Quay.io hosted container images

### PR DESCRIPTION
**Pull request by mrizzi**
https://issues.redhat.com/browse/WINDUP-2855

The "rendered" README is available at https://github.com/mrizzi/windup-openshift/blob/WINDUP-2855/README.md

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
All of those changes look fine. Did you consider changing some of the variable names e.g. DOCKER_IMAGES_USER to replace the "DOCKER" portion with QUAY or would that have mandated other changes too?
I'll test the templates in UpShift

**Comment by PhilipCattanach** [comment]
The web-template-empty-dir-executor.json deployed successfully and and analysis was executed successfully too.

**Comment by mrizzi** [comment]
> All of those changes look fine. Did you consider changing some of the variable names e.g. DOCKER_IMAGES_USER to replace the "DOCKER" portion with QUAY or would that have mandated other changes too?
> I'll test the templates in UpShift

That's a good point and I took a decision about this I'm happy to discuss.
I kept `DOCKER` word because it refers, for me, not to Docker Hub but to docker image as "technology".
Just like, for example, you still use `docker` command to push images to Quay repository.
So I kept the `DOCKER` word to reflect the technology rather than the image repository.
Does it make sense?

**Comment by PhilipCattanach** [comment]
Thanks Marco - yes that makes perfect sense. I'm happy with that.

**Pull request merged**
